### ISSUE TITLE
Fail2ban integration

### ISSUE THREAD

**Issue by doino-gretchenliev** [openbridge/nginx#16]
I want to suggest you to install Fail2ban tool or provide notes in the documentation how to integrate with the Nginx container. Right now I'm using log to file Nginx configuration and separate Fail2ban container.

**Comment by tspicer** [comment]
The typical use case I have seen is Fail2ban installed on the host. Can you describe this configuration you have?

**Comment by doino-gretchenliev** [comment]
I'm using your image with the following mount: `/host_mountpoint:/var/log/nginx`. And I'm also using [this](https://hub.docker.com/r/superitman/fail2ban) image with mount: `/host_mountpoint:/var/log/nginx`. The setup allows fail2ban tool to read nginx logs in order to limit/restrict traffic by modifying the host iptables. The fail2ban will require `--privileged`.

**Comment by tspicer** [comment]
If you want, you can modify the Dockerfile  and build the image to adjust logging
``` 
&& ln -sf /dev/stdout ${LOG_PREFIX}/access.log \
&& ln -sf /dev/stderr ${LOG_PREFIX}/error.log \
&& ln -sf /dev/stdout ${LOG_PREFIX}/blocked.log
```
I don't use fail2ban much so you may want to experiment how it interacts with the other services being run.
