### ISSUE TITLE
Certificate issue running localhost

### ISSUE THREAD

**Issue by dbrosy** [openbridge/nginx#18]
Hi,

I currently have a rancher based apache php stack running wordpress but looking for something with better performance etc

I'm trying to test out the wordpress stack but get an issue on start up with nginx server
I'm testing on a local vm and was expecting it to run under localhost. am I mistaken ?

I have been able to get rest working but nginx keeps restarting so i'm just looking at the nginx part

the error I get is: 

`nginx    | OK: All setup processes have completed. NGINX Service is now running...
nginx    | 2018/09/18 22:54:52 [emerg] 1#1: BIO_new_file("/etc/letsencrypt/live/localhost/fullchain.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/letsencrypt/live/localhost/fullchain.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
nginx    | nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/localhost/fullchain.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/letsencrypt/live/localhost/fullchain.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
nginx exited with code 1
`

Is it possible to run nginx without a Letsencrypt cert?

I have a Google cloud test server to try this on

**Comment by tspicer** [comment]
Hi,
Sorry for the delay in responding. It is possible to use a local cert. It leverages the paths of Lets Encrypt when it is not in use.

If you pass `NGINX_DEV_INSTALL=true` in the ENV file it should auto create temp SSL certs.

There is a section in the README about this:

```
You can set a collection of dummy files and certs for local testing:
* `NGINX_DEV_INSTALL` Set to `true` if you want self-signed SSL certs installed and "hello world" HTML and PHP pages installed. This is useful for testing.
* NOTE: Self-signed SSL certificates are always installed if the system does not detect here in the default cert location at `/etc/letsencrypt/live/${NGINX_SERVER_NAME}/`
```

**Comment by tspicer** [comment]
Also, if you can share your ENV file that would be helpful.
