### ISSUE TITLE
nginx: [emerg] BIO_new_file Error

### ISSUE THREAD

**Issue by Able2Code** [openbridge/nginx#25]
**Describe the bug**
Hi, after a fresh installation of nginx+php-fpm, nginx container stop trowing this error
<pre>
checksum: file /etc/letsencrypt/live/mapsgrabber.com/fullchain.pem is not regular file
/etc/monit.d/check_nginx:21: Cannot compute a checksum for file /etc/letsencrypt/live/mapsgrabber.com/fullchain.pem ''/usr/sbin/nginx -s reload''
 New Monit id: caff48aa9d2cef89f554dd5699cc3785
 Stored in '/root/.monit.id'
Starting Monit 5.25.1 daemon with http interface at [localhost]:2849
OK: All setup processes have completed. NGINX Service is now running...
2018/10/25 17:22:56 [emerg] 1#1: BIO_new_file("/etc/letsencrypt/live/mapsgrabber.com/fullchain.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/letsencrypt/live/mapsgrabber.com/fullchain.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/mapsgrabber.com/fullchain.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/letsencrypt/live/mapsgrabber.com/fullchain.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
</pre>

my env
<pre>
NGINX_DOCROOT=/usr/share/nginx/html
NGINX_SERVER_NAME=mapsgrabber.com
NGINX_CONFIG=php
PHP_FPM_UPSTREAM=localhost:9000
REDIS_UPSTREAM=redis:6379
NGINX_PROXY_UPSTREAM=localhost:8080
</pre>

maybe a permission error? i run docker with root user
**To Reproduce**
i used this docker yml
<pre>
version: '3.1'
services:
  nginx:
    image: openbridge/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs:
      - /var/cache
    volumes:
      - db_data:/usr/share/nginx/html
      #- certs:/etc/letsencrypt/live
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
    env_file:
      - ./env/stage.env
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Pettinell@2009
      MYSQL_DATABASE: mapsgra
      MYSQL_USER: root
      MYSQL_PASSWORD: Pettinell@2009
    tty: true
    volumes:
       - db_data:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  php-fpm:
    image: openbridge/ob_php-fpm
    container_name: php-fpm
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./env/stage.env
    ports:
      - 9001:9000
    tmpfs:
      - /var/cache
    tty: true
    volumes:
       - db_data:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
  redis:
    image: redis
    container_name: redis
    restart: always
volumes:
  db_data:
  certs:

</pre>

**Expected behavior**
docker logs nginx ... and i see the error above

**Desktop (please complete the following information):**
 - OS: Ubuntu + 
Docker version 18.06.1-ce, build e68fc7a + 
docker-compose version 1.22.0, build f46880fe

**Comment by tspicer** [comment]
It is saying that it can't find the SSL cert `/etc/letsencrypt/live/mapsgrabber.com/fullchain.pem`. Can you confirm that path is correct on your host to letsencrypt? List the contents `ls -al /etc/letsencrypt/live/`

Based on your config you are assuming to see `mapsgrabber.com`. 

Also, I always suggest mounting the exact files. This avoids problems like the one you are reporting as it forces you to know where the certs are on the host. 
```
    volumes:
      - /my/local/path:/usr/share/nginx/html
      - /etc/letsencrypt/live/www.openbridge.com/fullchain.pem:/etc/letsencrypt/live/www.openbridge.com/fullchain.pem
      - /etc/letsencrypt/live/www.openbridge.com/privkey.pem:/etc/letsencrypt/live/www.openbridge.com/privkey.pem
      - /etc/letsencrypt/live/www.openbridge.com/chain.pem:/etc/letsencrypt/live/www.openbridge.com/chain.pem
```

**Comment by Able2Code** [comment]
@tspicer , thank you, the nginx container stops after few seconds and i can't run any command. I'm new on docker, there is a way to prevent this stops or i must edit the entrypoint.sh?

**Comment by tspicer** [comment]
Did you resolve the SSL error? It will be helpful to understand if an issue was resolved and if we are reporting a new one :)

Hi, can you paste the output of `docker logs nginx` here? 

Also, can you also paste the contents of `ls -al /etc/letsencrypt/live/` if you did not resolve your SSL issue?

**Comment by tspicer** [comment]
On your host, can you run `ls -al /etc/letsencrypt/live/`?

**Comment by Able2Code** [comment]
now I understood: I thought the container was responsible for creating certificates.
Now, installed certbot, created the certificates and everything works fine.
Thanks for the time you have dedicated to me and I'm sorry!

**Comment by tspicer** [comment]
The container will only create self-signed certs for testing. Glad you have it solved.
