### ISSUE TITLE
ngx_http_geoip_module.so

### ISSUE THREAD

**Issue by CoolID2** [openbridge/nginx#40]
When I start the Docker image I get the following error message

nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_geoip_module.so" failed (Error loading shared library /etc/nginx/modules/ngx_http_geoip_module.so: No such file or directo
ry) in /etc/nginx/nginx.conf:1        

Can you help me ?

Here is my creation-config

docker create \
	--name=openbridge \
	-v /share/Container_Data/openbridge/etc/nginx:/etc/nginx \
    -v /share/Container_Data/openbridge/usr/share/nginx/html:/usr/share/nginx/html \
	-v /share/Container_Data/openbridge/var/log/nginx:/var/log/nginx \
	-v /share/Container_Data/SSL/${NGINX_SERVER_NAME}/fullchain.pem:/etc/letsencrypt/live/${NGINX_SERVER_NAME}/fullchain.pem:ro \
    -v /share/Container_Data/SSL/${NGINX_SERVER_NAME}/privkey.pem:/etc/letsencrypt/live/${NGINX_SERVER_NAME}/privkey.pem:ro \
    -v /share/Container_Data/SSL/${NGINX_SERVER_NAME}/chain.pem:/etc/letsencrypt/live/${NGINX_SERVER_NAME}/chain.pem:ro \
	-p 9980:80 -p 9443:443 \
	-e TZ=Europe/Berlin \
	-e NGINX_DOCROOT=/usr/share/nginx/html \
	-e NGINX_SERVER_NAME=top.secret.de \
	-e NGINX_CONFIG=php \
	-e NGINX_DEV_INSTALL=false \
	openbridge/nginx

**Comment by tspicer** [comment]
Hmm, which version are you using? latest?

**Comment by CoolID2** [comment]
Yes. 
2019/05/10 13:06:31

**Comment by tspicer** [comment]
Have you tried to comment out the line in your nginx.conf file?

`load_module                            /etc/nginx/modules/ngx_http_geoip_module.so`
to
`#load_module                            /etc/nginx/modules/ngx_http_geoip_module.so`?

**Comment by CoolID2** [comment]
Yes, but the file will be overwritten after an restart.

**Comment by tspicer** [comment]
Also, can to connect to your container via bash and run 
```bash
bash-4.4# ls -al /usr/local/share/GeoIP

drwxr-xr-x    2 www-data www-data      4096 May 23 19:15 .
drwxr-xr-x    1 root     root          4096 May 23 19:16 ..
-rw-r--r--    1 www-data www-data   1242574 May 23 19:15 GeoIP.dat
-rw-r--r--    1 www-data www-data  20539238 May 23 19:15 GeoLiteCity.dat
```
I want to confirm you have the legacy GeoIP files present.

**Comment by tspicer** [comment]
First, I want to see if the error still happens. Does it? If it works with issue, that is part of troubleshooting. 

Also, why would the file be overwritten? How are you managing your config files? I assume you are mounting them via `-v /share/Container_Data/openbridge/etc/nginx:/etc/nginx ` so the changes are not ephemeral,  but local to your config path `/share/Container_Data/openbridge/etc/nginx`.

I have run tests locally and do not have the error.

**Comment by CoolID2** [comment]
the container stops running after the error occured, so I can't connect to the container by bash.
I've mapped the path   /usr/local/share/GeoIP   but there are no such files you have been posted.

Even if the container stops I can see the nginx.conf. After a restart of the container, the commented-out line is active again.

It looks like every time I restart the container it reinitializes again.

**Comment by CoolID2** [comment]
**I tried this minimum configuration and I got an similar error. Maybe my config is wrong**

docker create \
	--name=openbridge \
	-v /share/Container_Data/openbridge/etc/nginx:/etc/nginx \
    -v /share/Container_Data/openbridge/usr/share/nginx/html:/usr/share/nginx/html \
	-v /share/Container_Data/openbridge//usr/local/share/GeoIP:/usr/local/share/GeoIP \
	-p 9980:80 -p 9443:443 \
	-e NGINX_CONFIG=html \
	-e NGINX_DEV_INSTALL=true \
	openbridge/nginx


**Here is the end of the log output:**

sent 62,997 bytes  received 92 bytes  126,178.00 bytes/sec                                                                                                                                               
total size is 62,727  speedup is 0.99                                                                                                                                                                    
sending incremental file list                                                                                                                                                                            
400.html                                                                                                                                                                                                 
401.html                                                                                                                                                                                                 
403.html                                                                                                                                                                                                 
404.html                                                                                                                                                                                                 
500.html                                                                                                                                                                                                 
501.html                                                                                                                                                                                                 
502.html                                                                                                                                                                                                 
503.html                                                                                                                                                                                                 
504.html                                                                                                                                                                                                 
                                                                                                                                                                                                         
sent 37,030 bytes  received 187 bytes  74,434.00 bytes/sec                                                                                                                                               
total size is 36,501  speedup is 0.98                                                                                                                                                                    
set daemon 10                                                                                                                                                                                            
    with START DELAY 15                                                                                                                                                                                  
set pidfile /run/monit.pid                                                                                                                                                                               
set statefile /run/monit.state                                                                                                                                                                           
set httpd port 2849 and                                                                                                                                                                                  
    use address localhost                                                                                                                                                                                
    allow localhost                                                                                                                                                                                      
set logfile syslog                                                                                                                                                                                       
set eventqueue                                                                                                                                                                                           
    basedir /var/run                                                                                                                                                                                     
    slots 100                                                                                                                                                                                            
include /etc/monit.d/*                                                                                                                                                                                   
/etc/monit.d/check_nginx:24: syntax error 'if'                                                                                                                                                           
2019/05/23 20:22:01 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_geoip_module.so" failed (Error loading shared library /etc/nginx/modules/ngx_http_geoip_module.so: No such file or directory) in /
etc/nginx/nginx.conf:1                                                                                                                                                                                   
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_geoip_module.so" failed (Error loading shared library /etc/nginx/modules/ngx_http_geoip_module.so: No such file or directory) in /etc/nginx/nginx.co
nf:1

**Comment by tspicer** [comment]
It is hard for me to know what is going on in your local environment. You can change the Docker file CMD to bypass the nginx command. If you are not clear on how to do this, then you can state so.

Why are you mapping the path for GeoIP? I never suggested that you map the files GeoIP files. I just wanted to see if they are resident in your build. If you look at the Dockerfile it clearly indicates the GeoIP files are pulled from this repo:

```
  && echo 'adding /usr/local/share/GeoIP/GeoIP.dat database' \
  && wget -N https://raw.githubusercontent.com/openbridge/nginx/master/geoip/GeoLiteCity.dat.gz \
  && wget -N https://raw.githubusercontent.com/openbridge/nginx/master/geoip/GeoIP.dat.gz \
  && gzip -d GeoIP.dat.gz \
  && gzip -d GeoLiteCity.dat.gz \
  && mkdir /usr/local/share/GeoIP/ \
  && mv GeoIP.dat /usr/local/share/GeoIP/ \
  && mv GeoLiteCity.dat /usr/local/share/GeoIP/ \
  && chown -R www-data:www-data /usr/local/share/GeoIP/ \
```
Look into the `/geoip/` you will see the dat files.

Did you follow the build instructions? In the first few sentences, it describes either pulling the image or running. For example, if you want NGINX `1.16.0`
```
docker build --build-arg "NGINX_VERSION=1.16.0" -t openbridge/nginx .
```
Can you detail what you did?

Also, since you are saying you want to use the PHP configs, please paste the content of the
 `conf/php/nginx.conf` file. As I indicated, you must comment out the line in question.

I won't be able to help you if you can't walk-thru the QA steps I'm asking you to undertake.

**Comment by tspicer** [comment]
One last comment, what does the name `top.secret.de` resolve too? Are you deploying this test to a server that resolves with this DNS? Are you running this locally and resolving this?
