### ISSUE TITLE
I want to use this dockers for django.

### ISSUE THREAD

**Issue by bluebamus** [openbridge/nginx#55]
**Is your feature request related to a problem? Please describe.**
I want to use this docker for django and flask using the uwsgi.
just following the guide on your git-book, I hope to work everything which are the redis and nginx modue etc.

**Describe the solution you'd like**
I need your the nginx performance guide to use django or flask.
and the docker too.

it's so amazing docker source here.
So I'd like to use everything.

Currently I'm using php but I have mind to use python platform too.
Of course, using your docker.

So I hope that you will get a mind to make new branches for python platform :)

**Comment by tspicer** [comment]
@bluebamus the configurations are plug-n-play. This means you are free to define your own configuration bundles for Python or anything else. Simply reference the config path in your settings and you are good to go. The default project provided a number of examples of this. We would welcome the community development of others, so if you want to version what is present for Python, please feel empowered to do so. This is the intent for providing the framework like this, so it can be customized as needed.
