### ISSUE TITLE
multiple site setting at nginx env 

### ISSUE THREAD

**Issue by bluebamus** [openbridge/nginx#56]
**Is your feature request related to a problem? Please describe.**

if I want to run several web site service, How can I set the compose file and env file?

Normally I am using each pool config files in php-fpm folder and conf files in nginx at general case.

So, If you know How I can handle several files for nginx, I can manage it.

**Comment by raulillana** [comment]
@bluebamus did you get it to work?

**Comment by tspicer** [comment]
hi @bluebamus, as I stated in another issue you posted the configs are plug and play. We have some examples of HTML, PHP...as references. Nothing prevents you from defining your own NGINX config structure and model. You are welcome to reimagine those configs in whatever manner is needed.
