### ISSUE TITLE
how can I use the docker image of  "openbridge/ob_php-fpm" 

### ISSUE THREAD

**Issue by bluebamus** [openbridge/nginx#57]
I don't understand how I can make connection between nginx container and php-fpm container.

I did set as bellow 

NGINX_SERVER_NAME = a.com www.a.com
NGINX_APP_PLUGIN = 
NGINX_CONFIG=php
NGINX_BAD_BOTS=true
NGINX_DEV_INSTALL=true
PHP_FPM_UPSTEAM=localhost:9000
REDIS_UPSTREAM=redis:6379
NGINX_PROXY_UPSTREAM=localhost:8080
NGINX_DOCTOO=/usr/share/nginx/html
NGINX_CDN_HOST=a.com

I couldn't test with localhost mysql till now...

I need your advice bro.. :)

**Comment by tspicer** [comment]
Do you have a docker-compose for all the services? It is hard to comment on only an ENV file for Nginx. Without understanding your topology for your environment I can't provide suggestions.
