### ISSUE TITLE
monit always failed at 8080 port check

### ISSUE THREAD

**Issue by huynq2007** [openbridge/nginx#59]
**Describe the bug**
When you run with the `html` config. monit will run `conf/html/monit/check_nginx` script to check upstream proxy port. Since the proxy is local to the container but monit run the check with `NGINX_SERVER_NAME` address. There is possibility that it will be failed.

**To Reproduce**
1. Confirm the `conf/html/monit/check_nginx`
2. You will see the command `if failed port 8080 for 3 cycles then exec "/usr/bin/env bash -c '/usr/sbin/nginx -s stop'"` (line 36)

**Expected behavior**
remove this line as it is supposed that 8080 port will always be locally opened. Therefore, not necessary to check this port.

**Screenshots**
The monit web interface show 8080 port check will always be failed.
<img width="1617" alt="Screen Shot 2020-04-14 at 13 44 41" src="https://user-images.githubusercontent.com/39758800/79187139-77c66780-7e56-11ea-9300-be54882b4877.png">

**Comment by tspicer** [comment]
I think this was an errant addition as I do not have it locally. I will remove.

**Comment by tspicer** [comment]
If you can confirm this fixes your issue I will close. Thanks

**Comment by huynq2007** [comment]
`conf/html/monit/check_nginx` does have that check but `conf/php/monit/check_nginx` doesn't
Therefore the issue only happened when we running in `html` config
I remove that line and the issue is fixed.
