### ISSUE TITLE
Nginx Pagespeed module?

### ISSUE THREAD

**Issue by thijskaspers** [openbridge/nginx#65]
Hello and thanks for creating this image!

I see the project has a Dockerfile-pagespeed. Can that be used, or is it deprecated, since it hasn't had an update in 2 years? We love your image, but would like to have the pagespeed module for nginx installed, which has to be included at buildtime.

**Comment by tspicer** [comment]
Hello,
It was just an early prototype. What I found was that the performance of the current setup was equal or outperformed the use of pagespeed given the use of nginx and redis.

Still looks like there are unresolved issues almost 4 years after being reported:
https://github.com/apache/incubator-pagespeed-ngx/issues/1181

Feel free to dust off the docker file and see how it goes. If you get a working model please make a pull request, it would be great to have that option here.
